# NumPy - Numerical Python 

Advantages of Numpy Arrays over list and tuples: 

    1. Allows several Mathematical Operations
    2. Faster Operations

In [1]:
import numpy as np

In [2]:
from time import process_time

In [ ]:
# Time taken by a list
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time  = process_time()

print(end_time - start_time)


0.0


In [7]:
# Option 1: Wrap generator in a list
np_array = np.array([i for i in range(10000)])

# Option 2: Use NumPy's arange (best)
np_array = np.arange(10000)

start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time - start_time)

0.0


In [2]:
np_arr = np.array([1,2,3,4,5])
print(np_arr)
type(np_arr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# 1 dim array

a = np.array([1,2,3,4,5])
print(a)
print(a.shape) 
print(a.ndim)

[1 2 3 4 5]
(5,)
1


In [ ]:
# 2 dim arrays

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [8]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [9]:
# Initial Placeholders in numpy arrays

# numpy array of zeroes 

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# numpy array of ones

x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:

# array of a particular value

x = np.full((5,4),5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
# identity matrix 

x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:

# numpy array with random values

x = np.random.random((3,4)) # all values is between 0 and 1
print(x)



[[0.73151291 0.71025975 0.38270151 0.17566486]
 [0.14145465 0.41618426 0.37993665 0.47970805]
 [0.89764277 0.74986833 0.14611706 0.4769601 ]]


In [ ]:

# random integer value arrays within a specific range

x = np.random.randint(10,100,(3,5)) # range - start,end dim-(3,5)(row,col)
print(x)

[[83 45 95 59 82]
 [50 58 35 70 70]
 [33 83 49 22 31]]


In [ ]:
# array of evenly spaced value --> Specifying number of values

x = np.linspace(10,30,6) # values between 10 - 30 , 6 values
print(x)

[10. 14. 18. 22. 26. 30.]


In [21]:
# array of evenly spaced value --> specifying the step

x = np.arange(10,30,5) # range (10,30) step (5)
print(x)

[10 15 20 25]


In [22]:
# convert list to array

list1 = [10,20,30,40,50]
np_array = np.asarray(list1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [ ]:
# Analysing numpy array

c = np.random.randint(10,90,(5,5)) # value from 10-90 , 5x5 matrix
print(c)

print(c.shape) # rows columns
print(c.ndim)  # dimensions
print(c.size)  # no. of elements
print(c.dtype) # datatype of values present in arr


[[55 69 49 22 14]
 [18 63 78 42 67]
 [28 74 71 81 22]
 [75 31 38 49 69]
 [59 39 44 42 18]]
(5, 5)
2
25
int32


In [ ]:
# Mathematical Operations on numpy arrays 

# Addition of list - concatenate elements of lists or joins two lists 

# But in numpy arrays elements get actually added.

a = np.arange(10,30,5)
print(a)
b = np.arange(30,50,5)
print(b)

print(a+b)



[10 15 20 25]
[30 35 40 45]
[40 50 60 70]


In [29]:
a = np.random.randint(10,100,(3,4))
print(a)
b = np.random.randint(10,100,(3,4))
print(b)
print(a+b)

[[55 79 73 80]
 [98 83 86 21]
 [70 79 88 95]]
[[64 85 98 93]
 [80 52 91 15]
 [81 88 13 92]]
[[119 164 171 173]
 [178 135 177  36]
 [151 167 101 187]]


In [30]:
print(a-b)
print(a*b)
print(a/b)

[[ -9  -6 -25 -13]
 [ 18  31  -5   6]
 [-11  -9  75   3]]
[[3520 6715 7154 7440]
 [7840 4316 7826  315]
 [5670 6952 1144 8740]]
[[0.859375   0.92941176 0.74489796 0.86021505]
 [1.225      1.59615385 0.94505495 1.4       ]
 [0.86419753 0.89772727 6.76923077 1.0326087 ]]


In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[119 164 171 173]
 [178 135 177  36]
 [151 167 101 187]]
[[ -9  -6 -25 -13]
 [ 18  31  -5   6]
 [-11  -9  75   3]]
[[3520 6715 7154 7440]
 [7840 4316 7826  315]
 [5670 6952 1144 8740]]
[[0.859375   0.92941176 0.74489796 0.86021505]
 [1.225      1.59615385 0.94505495 1.4       ]
 [0.86419753 0.89772727 6.76923077 1.0326087 ]]


In [33]:
# Array manipulation

array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

trans =np.transpose(array)
print(trans)
print(trans.shape)

[[0 8 6]
 [0 8 7]]
(2, 3)
[[0 0]
 [8 8]
 [6 7]]
(3, 2)


In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 9 9]
 [1 2 6]]
(2, 3)
[[7 1]
 [9 2]
 [9 6]]
(3, 2)


In [ ]:
a= np.random.randint(0,10,(2,3))
 
print(a)
 
print(a.shape)
 
b = a.reshape(3,2)
 
print(b)

[[4 1 6]
 [4 2 3]]
(2, 3)
[[4 1]
 [6 4]
 [2 3]]
